export const weather = {
    FETCH : "FETCH",
    RECEIVE: "RECEIVE",
    FAIL_RECEIVE: "FAIL_RECEIVE",
    FETCH_FORECAST : "FETCH_FORECAST",
    RECEIVE_FORECAST: "RECEIVE_FORECAST",
    FAIL_RECEIVE_FORECAST: "FAIL_RECEIVE_FORECAST",
}

export const blogs = {
    FETCH_ALL : "FETCH_ALL",
    RECEIVE_ALL: "RECEIVE_ALL_BLOGS",
    FAIL_RECEIVE_ALL: "FAIL_RECEIVE_ALL",
    FETCH : "FETCH",
    RECEIVE: "RECEIVE_BLOG",
    FAIL_RECEIVE: "FAIL_RECEIVE_BLOG",
}

export const loginConstants = {
    LOGIN_SUCCEED: "LOGIN_SUCCEED",
    LOGIN_FAILED: "LOGIN_FAILED"
}